global:
  resolve_timeout: 5m
route:
  receiver: webhook_receiver
receivers:
    - name: webhook_receiver
      webhook_configs:
        - url: 'https://webhook.site/8dd69597-efa5-40d5-aac7-1eec74ff1e5e'
          send_resolved: false