global:
  resolve_timeout: 5m

route:
  receiver: 'slack-notification'

receivers:
    - name: 'slack-notification'
      slack_configs:
        - send_resolved: true
          username: 'Alertmanager'
          channel: '#lab-o2b-observability'
          api_url: 'https://hooks.slack.com/services/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'