global:
  scrape_interval: 15s
  external_labels:
    monitor: 'app'

rule_files:
  - rules.yml

alerting:
  alertmanagers:
   - static_configs:
     - targets: ['localhost:9093']

scrape_configs:
- job_name: 'prometheus'
  static_configs:
    - targets: ['localhost:9090']

- job_name: 'app'
  static_configs:
    - targets: ['kyabey.pythonanywhere.com']